-- Esta migration foi abandonada: criar o trigger manualmente via SQL
-- (supabase_functions.http_request) falha com "schema supabase_functions
-- does not exist" em projetos que nunca usaram Database Webhooks antes —
-- esse schema só é provisionado pelo próprio painel do Supabase na
-- primeira vez que a feature é habilitada, não por uma migration comum.
--
-- Configuração real (feita pelo painel, não por SQL):
--   Database → Webhooks → "Enable Webhooks" (se for a primeira vez) →
--   Create a new webhook:
--     Name:          notificar_novo_cadastro
--     Table:         public.perfis
--     Events:        Insert (só)
--     Webhook type:  Supabase Edge Functions
--     Edge Function: notificar-novo-cadastro
--
-- Isso cria, por trás dos panos, o mesmo tipo de trigger que esta
-- migration tentava criar à mão — só que com a infraestrutura
-- (schema supabase_functions, extensão pg_net) já provisionada
-- corretamente pelo Supabase.
--
-- A condição "só quando status_aprovacao = 'pendente'" não dá pra
-- configurar na UI de Webhooks (ela só filtra por tabela + evento), mas
-- não faz falta: todo perfil novo já nasce 'pendente' (gatilho
-- handle_new_user, migration 0002), e a Edge Function
-- (supabase/functions/notificar-novo-cadastro/index.ts) rebusca o
-- perfil e confere o status antes de enviar o e-mail — a checagem existe,
-- só que no código da function em vez de no trigger.
--
-- Não recrie esse trigger via SQL depois de configurar o webhook pela
-- UI — faria o e-mail ser enviado duas vezes por cadastro.
select 1; -- no-op: mantém o número de sequência das migrations sem alterar o schema
